[package]
name = "pocketbrain"
description = "A fast Brainfuck interpreter"
license = "MIT"
authors = ["Mahad Kalam"]
version = "0.1.1"
edition = "2021"

[dev-dependencies]
pretty_assertions = "1.4.1"

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
